### ISSUE TITLE
Missing suse12 packages

### ISSUE THREAD

**Issue by noly** [newrelic/fluent-bit-package#26]
## Description
We are currently missing supported service package for suse12.
We only provide packages for suse12 sp5, customer can manually installed as workaround.

## Steps to Reproduce
New customers: 
- Install infrastructure agent on suse12 sp4, 
- Provide a tail log configuration under `logging.d` folder
- Notice error message in agent logs:
```
time="2021-11-24T19:02:24-03:00" level=debug msg="Fluent Bit exe not found." component=integrations.Supervisor fbExePath=/opt/td-agent-bit/bin/td-agent-bit process=log-forwarder
time="2021-11-24T19:02:24-03:00" level=debug msg="Log forwarder is not available for this platform. The agent will start without log forwarding support." component=AgentService service=newrelic-infra
```

Already installed agents:
- From infrastructure agent v1.16.1 update to latest agent version,
- Notice error message in agent logs:
```
time="2021-11-24T19:02:24-03:00" level=debug msg="Fluent Bit exe not found." component=integrations.Supervisor fbExePath=/opt/td-agent-bit/bin/td-agent-bit process=log-forwarder
time="2021-11-24T19:02:24-03:00" level=debug msg="Log forwarder is not available for this platform. The agent will start without log forwarding support." component=AgentService service=newrelic-infra
```

## Expected Behavior
Provide support for all Suse service pack versions. SUSE12.1 SUSE12.2 SUSE12.3 SUSE12.4

**Comment by danybmx** [comment]
Hi @noly, I'm closing this as we already have support for those OS. Thanks a lot for the contribution and worrying about sles users.
